/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ggiz_view_eeprom_ComPort */

#ifndef _Included_net_ggiz_view_eeprom_ComPort
#define _Included_net_ggiz_view_eeprom_ComPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ggiz_view_eeprom_ComPort
 * Method:    readDataExtern
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_net_ggiz_view_eeprom_ComPort_readDataExtern
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
